import type { VehicleDetailReport } from "@/types/features/reports/reports-vehicle.types"
import {
  VehicleType,
  VehicleStatus,
  AlertPriority,
  TirePosition,
} from "@/types/features/reports/reports.enum"

export const mockVehicleDetailReport: VehicleDetailReport = {
  reportInfo: {
    reportId: "RPT-VH1003-2025-10-001",
    reportType: "vehicle_detail",
    vehicleId: "VH-1003",
    generatedAt: "2025-10-30T09:00:00Z",
    period: {
      start: "2025-10-01T00:00:00Z",
      end: "2025-10-30T23:59:59Z",
    },
  },

  vehicleInfo: {
    vehicleId: "VH-1003",
    type: VehicleType.EXCAVATOR,
    brand: "Komatsu",
    model: "PC200-11",
    plateNumber: "Tokyo 300-1003",
    manufactureYear: 2023,
    engineHours: 2456,
    odometer: 18234,
    fuelType: "diesel",
    company: "BANF",
    primaryOperator: "Tanaka Hiroshi",
    status: VehicleStatus.ACTIVE,
    gpsDevice: "EDG-MGRGW645-8760F961-209B",
    lastGpsUpdate: "2025-10-30T08:55:00Z",
    numberOfTires: 4,
    canBitrate: "500 Kbps",
  },

  performanceMetrics: {
    period: "Last 30 Days",
    metrics: {
      availability: {
        value: 92.3,
        target: 95.0,
        unit: "%",
        status: "below_target",
      },
      utilization: {
        value: 78.5,
        target: 80.0,
        unit: "%",
        status: "below_target",
      },
      fuelEfficiency: {
        value: 18.2,
        target: 17.0,
        unit: "L/hr",
        status: "above_target",
      },
      avgSpeed: {
        value: 12.4,
        target: 15.0,
        unit: "km/h",
        status: "below_target",
      },
      operatingHoursPerDay: {
        value: 7.2,
        target: 8.0,
        unit: "hours",
        status: "below_target",
      },
      idleTime: {
        value: 22.5,
        target: 20.0,
        unit: "%",
        status: "above_target",
      },
      productivityScore: {
        value: 85.2,
        target: 90.0,
        unit: "points",
        status: "monitor",
      },
      safetyScore: {
        value: 94.5,
        target: 95.0,
        unit: "points",
        status: "monitor",
      },
    },
  },

  activeAlerts: [
    {
      id: "ALT-001",
      priority: AlertPriority.HIGH,
      type: "Tire Pressure",
      description: "Front Left tire pressure low (85 psi)",
      detectedAt: "2025-10-30T06:30:00Z",
      actionRequired: "Immediate inspection and inflation required",
    },
    {
      id: "ALT-002",
      priority: AlertPriority.MEDIUM,
      type: "Maintenance Due",
      description: "250hr service due in 44 hours",
      detectedAt: "2025-10-30T00:00:00Z",
      actionRequired: "Schedule service appointment",
    },
    {
      id: "ALT-003",
      priority: AlertPriority.LOW,
      type: "Fuel Efficiency",
      description: "Fuel consumption 7% above average",
      detectedAt: "2025-10-27T14:00:00Z",
      actionRequired: "Monitor trend and investigate if persists",
    },
  ],

  operatingHistory: [
    {
      date: "2025-10-29",
      startTime: "06:00",
      endTime: "16:00",
      totalHours: 10.0,
      operatingHours: 8.2,
      idleHours: 1.8,
      distance: 98.4,
      fuelUsed: 149.2,
      fuelRate: 18.2,
      avgLoad: 75.5,
      maxSpeed: 22.0,
      events: "Normal operation",
    },
    {
      date: "2025-10-28",
      startTime: "07:00",
      endTime: "17:30",
      totalHours: 10.5,
      operatingHours: 8.5,
      idleHours: 2.0,
      distance: 102.0,
      fuelUsed: 157.3,
      fuelRate: 18.5,
      avgLoad: 78.2,
      maxSpeed: 24.0,
      events: "Hard brake x2",
    },
    {
      date: "2025-10-27",
      startTime: "06:30",
      endTime: "15:30",
      totalHours: 9.0,
      operatingHours: 7.5,
      idleHours: 1.5,
      distance: 86.3,
      fuelUsed: 135.0,
      fuelRate: 18.0,
      avgLoad: 72.8,
      maxSpeed: 21.5,
      events: "Over speed x1",
    },
    {
      date: "2025-10-26",
      startTime: "06:00",
      endTime: "16:30",
      totalHours: 10.5,
      operatingHours: 8.8,
      idleHours: 1.7,
      distance: 110.0,
      fuelUsed: 158.4,
      fuelRate: 18.0,
      avgLoad: 80.1,
      maxSpeed: 23.0,
      events: "Normal operation",
    },
    {
      date: "2025-10-25",
      startTime: "07:00",
      endTime: "17:00",
      totalHours: 10.0,
      operatingHours: 8.0,
      idleHours: 2.0,
      distance: 96.0,
      fuelUsed: 144.0,
      fuelRate: 18.0,
      avgLoad: 74.0,
      maxSpeed: 20.0,
      events: "High idle time",
    },
  ],

  tireAnalysis: {
    currentStatus: [
      {
        position: TirePosition.FL,
        tireId: "TR-2456",
        brand: "Bridgestone",
        model: "VMTS",
        size: "20.5R25",
        installDate: "2024-06-15",
        pressure: {
          current: 85,
          target: 100,
          status: "low",
        },
        temperature: 52,
        treadDepth: {
          current: 28,
          original: 40,
        },
        wearPercentage: 30,
        estimatedRemainingLife: 4200,
      },
      {
        position: TirePosition.FR,
        tireId: "TR-2457",
        brand: "Bridgestone",
        model: "VMTS",
        size: "20.5R25",
        installDate: "2024-06-15",
        pressure: {
          current: 98,
          target: 100,
          status: "ok",
        },
        temperature: 54,
        treadDepth: {
          current: 27,
          original: 40,
        },
        wearPercentage: 32.5,
        estimatedRemainingLife: 4050,
      },
      {
        position: TirePosition.RL,
        tireId: "TR-2458",
        brand: "Bridgestone",
        model: "VMTS",
        size: "20.5R25",
        installDate: "2024-08-20",
        pressure: {
          current: 102,
          target: 100,
          status: "ok",
        },
        temperature: 55,
        treadDepth: {
          current: 32,
          original: 40,
        },
        wearPercentage: 20,
        estimatedRemainingLife: 4800,
      },
      {
        position: TirePosition.RR,
        tireId: "TR-2459",
        brand: "Bridgestone",
        model: "VMTS",
        size: "20.5R25",
        installDate: "2024-08-20",
        pressure: {
          current: 100,
          target: 100,
          status: "ok",
        },
        temperature: 53,
        treadDepth: {
          current: 31,
          original: 40,
        },
        wearPercentage: 22.5,
        estimatedRemainingLife: 4650,
      },
    ],
    replacementHistory: [
      {
        position: TirePosition.FL,
        removedDate: "2024-06-14",
        tireId: "TR-1892",
        totalHours: 3250,
        totalDistance: 28450,
        removalReason: "scheduled",
        finalTread: 8.5,
        avgWearRate: 9.8,
        cost: 2850,
        performanceRating: "good",
      },
      {
        position: TirePosition.FR,
        removedDate: "2024-06-14",
        tireId: "TR-1893",
        totalHours: 3250,
        totalDistance: 28450,
        removalReason: "scheduled",
        finalTread: 7.2,
        avgWearRate: 10.2,
        cost: 2850,
        performanceRating: "good",
      },
      {
        position: TirePosition.RL,
        removedDate: "2024-08-19",
        tireId: "TR-2104",
        totalHours: 2890,
        totalDistance: 24200,
        removalReason: "damage",
        finalTread: 12.0,
        avgWearRate: 9.7,
        cost: 2850,
        performanceRating: "fair",
      },
      {
        position: TirePosition.RR,
        removedDate: "2024-08-19",
        tireId: "TR-2105",
        totalHours: 2890,
        totalDistance: 24200,
        removalReason: "wear",
        finalTread: 5.5,
        avgWearRate: 11.9,
        cost: 2850,
        performanceRating: "fair",
      },
    ],
  },

  maintenanceRecords: {
    upcoming: [
      {
        serviceType: "250hr Service",
        dueDate: "2025-11-05",
        dueHours: 2500,
        currentHours: 2456,
        hoursRemaining: 44,
        estimatedDuration: 4,
        estimatedCost: 850,
        priority: AlertPriority.MEDIUM,
        partsRequired: [
          "Engine Oil",
          "Oil Filter",
          "Air Filter",
          "Fuel Filter",
        ],
        status: "scheduled",
        notes: "Regular 250hr interval service",
      },
      {
        serviceType: "Hydraulic System Check",
        dueDate: "2025-11-15",
        dueHours: 2600,
        currentHours: 2456,
        hoursRemaining: 144,
        estimatedDuration: 2,
        estimatedCost: 350,
        priority: AlertPriority.LOW,
        partsRequired: ["Hydraulic fluid"],
        status: "pending",
        notes: "Check hydraulic pressure and fluid level",
      },
      {
        serviceType: "Track Inspection",
        dueDate: "2025-11-20",
        dueHours: 2650,
        currentHours: 2456,
        hoursRemaining: 194,
        estimatedDuration: 1,
        estimatedCost: 150,
        priority: AlertPriority.LOW,
        partsRequired: [],
        status: "pending",
        notes: "Visual inspection of tracks and undercarriage",
      },
    ],
    history: [
      {
        date: "2025-09-15",
        serviceType: "250hr Service",
        hoursAtService: 2250,
        duration: 3.5,
        cost: 820,
        partsReplaced: ["Engine Oil", "Air Filter"],
        laborHours: 3.5,
        technician: "T. Yamamoto",
        result: "completed",
        nextDue: "2500hr",
        notes: "Normal wear observed, all systems functioning properly",
      },
      {
        date: "2025-07-20",
        serviceType: "500hr Service",
        hoursAtService: 2000,
        duration: 6.0,
        cost: 1450,
        partsReplaced: ["All filters", "Drive belts", "Coolant"],
        laborHours: 6.0,
        technician: "K. Suzuki",
        result: "completed",
        nextDue: "2500hr",
        notes: "Major service completed, machine in good condition",
      },
      {
        date: "2025-06-05",
        serviceType: "Hydraulic Pump Repair",
        hoursAtService: 1892,
        duration: 8.0,
        cost: 2100,
        partsReplaced: ["Main hydraulic pump", "Hydraulic fluid", "Seals"],
        laborHours: 8.0,
        technician: "T. Yamamoto",
        result: "completed",
        nextDue: "N/A",
        notes: "Pump failure due to contamination, system flushed and refilled",
      },
      {
        date: "2025-05-10",
        serviceType: "250hr Service",
        hoursAtService: 1750,
        duration: 3.0,
        cost: 780,
        partsReplaced: ["Engine Oil", "Fuel Filter"],
        laborHours: 3.0,
        technician: "K. Suzuki",
        result: "completed",
        nextDue: "2000hr",
        notes: "Routine maintenance, no issues found",
      },
    ],
  },

  costAnalysis: {
    monthlyCosts: [
      {
        month: "May 2025",
        fuel: 3850,
        maintenance: 780,
        tires: 0,
        operator: 3200,
        insurance: 450,
        other: 150,
        total: 8430,
        costPerHour: 52.69,
      },
      {
        month: "Jun 2025",
        fuel: 4120,
        maintenance: 2100,
        tires: 0,
        operator: 3200,
        insurance: 450,
        other: 200,
        total: 10070,
        costPerHour: 62.94,
      },
      {
        month: "Jul 2025",
        fuel: 4280,
        maintenance: 1450,
        tires: 0,
        operator: 3200,
        insurance: 450,
        other: 180,
        total: 9560,
        costPerHour: 59.75,
      },
      {
        month: "Aug 2025",
        fuel: 3980,
        maintenance: 350,
        tires: 11400,
        operator: 3200,
        insurance: 450,
        other: 220,
        total: 19600,
        costPerHour: 122.5,
      },
      {
        month: "Sep 2025",
        fuel: 4050,
        maintenance: 820,
        tires: 0,
        operator: 3200,
        insurance: 450,
        other: 175,
        total: 8695,
        costPerHour: 54.34,
      },
      {
        month: "Oct 2025",
        fuel: 4180,
        maintenance: 0,
        tires: 0,
        operator: 3200,
        insurance: 450,
        other: 195,
        total: 8025,
        costPerHour: 50.16,
      },
    ],
    costByActivity: [
      {
        activity: "Excavation",
        hours: 850,
        fuelCost: 12750,
        totalCost: 18500,
        costPerHour: 21.76,
      },
      {
        activity: "Loading",
        hours: 420,
        fuelCost: 5880,
        totalCost: 8200,
        costPerHour: 19.52,
      },
      {
        activity: "Grading",
        hours: 280,
        fuelCost: 3640,
        totalCost: 5100,
        costPerHour: 18.21,
      },
      {
        activity: "Idle/Standby",
        hours: 180,
        fuelCost: 900,
        totalCost: 2400,
        costPerHour: 13.33,
      },
      {
        activity: "Transport",
        hours: 95,
        fuelCost: 1425,
        totalCost: 2100,
        costPerHour: 22.11,
      },
    ],
    totalCost: {
      period: "Last 6 Months",
      total: 64380,
      avgPerHour: 66.84,
      avgPerKm: 3.53,
    },
  },

  performanceTrends: [
    {
      week: "W40 (09/30)",
      weekNumber: 40,
      startDate: "2025-09-30",
      availability: 94.2,
      utilization: 82.5,
      fuelEfficiency: 17.8,
      productivityIndex: 88.5,
      operatingHours: 42,
      distance: 504,
      idleTime: 18.5,
      eventsCount: 3,
      costPerHour: 52.5,
      score: 86.4,
    },
    {
      week: "W41 (10/07)",
      weekNumber: 41,
      startDate: "2025-10-07",
      availability: 92.8,
      utilization: 78.2,
      fuelEfficiency: 18.2,
      productivityIndex: 85.2,
      operatingHours: 38,
      distance: 456,
      idleTime: 21.0,
      eventsCount: 5,
      costPerHour: 54.75,
      score: 83.8,
    },
    {
      week: "W42 (10/14)",
      weekNumber: 42,
      startDate: "2025-10-14",
      availability: 91.5,
      utilization: 76.8,
      fuelEfficiency: 18.5,
      productivityIndex: 84.0,
      operatingHours: 40,
      distance: 480,
      idleTime: 23.5,
      eventsCount: 4,
      costPerHour: 56.2,
      score: 82.5,
    },
    {
      week: "W43 (10/21)",
      weekNumber: 43,
      startDate: "2025-10-21",
      availability: 93.0,
      utilization: 80.5,
      fuelEfficiency: 18.0,
      productivityIndex: 86.8,
      operatingHours: 45,
      distance: 540,
      idleTime: 19.5,
      eventsCount: 2,
      costPerHour: 51.8,
      score: 85.2,
    },
    {
      week: "W44 (10/28)",
      weekNumber: 44,
      startDate: "2025-10-28",
      availability: 95.0,
      utilization: 83.0,
      fuelEfficiency: 17.9,
      productivityIndex: 89.2,
      operatingHours: 43,
      distance: 516,
      idleTime: 17.0,
      eventsCount: 3,
      costPerHour: 50.4,
      score: 87.8,
    },
  ],

  eventLog: [
    {
      id: "EVT-001",
      timestamp: "2025-10-30T08:15:00Z",
      eventType: "hard_brake",
      severity: AlertPriority.MEDIUM,
      description: "Hard brake detected during normal operation",
      location: "Site A - Zone 3",
      speed: 18,
      operator: "T. Tanaka",
      actionTaken: "Event logged for review",
    },
    {
      id: "EVT-002",
      timestamp: "2025-10-29T14:30:00Z",
      eventType: "long_idle",
      severity: AlertPriority.LOW,
      description: "Extended idle time detected (25 minutes)",
      location: "Site A - Zone 2",
      speed: 0,
      operator: "H. Suzuki",
      actionTaken: "None required",
    },
    {
      id: "EVT-003",
      timestamp: "2025-10-28T11:45:00Z",
      eventType: "over_speed",
      severity: AlertPriority.HIGH,
      description: "Speed exceeded limit (24 km/h in 20 km/h zone)",
      location: "Site A - Zone 1",
      speed: 24,
      operator: "T. Tanaka",
      actionTaken: "Warning issued to operator",
    },
    {
      id: "EVT-004",
      timestamp: "2025-10-27T09:20:00Z",
      eventType: "maintenance_alert",
      severity: AlertPriority.MEDIUM,
      description: "250hr service approaching (50 hours remaining)",
      location: "N/A",
      operator: "System",
      actionTaken: "Maintenance scheduled",
    },
    {
      id: "EVT-005",
      timestamp: "2025-10-26T16:00:00Z",
      eventType: "geofence_alert",
      severity: AlertPriority.LOW,
      description: "Vehicle exited designated work zone",
      location: "Site A - Boundary",
      speed: 12,
      operator: "K. Yamamoto",
      actionTaken: "Logged - authorized exit",
    },
  ],
}

// API Response wrapper
export const mockVehicleDetailApiResponse: VehicleDetailReport =
  mockVehicleDetailReport

// Report Generation Response Mock
export const mockGenerateReportResponse = {
  reportId: "RPT-VH1003-2025-10-001",
  downloadUrl:
    "https://api.fms.example.com/reports/download/RPT-VH1003-2025-10-001",
  expiresAt: "2025-10-31T09:00:00Z",
  format: "xlsx" as const,
  sizeInBytes: 524288,
}
