import type { FleetOverviewReport } from "@/types/features/reports/reports-fleet.types"
import {
  VehicleType,
  AlertPriority,
  TirePosition,
} from "@/types/features/reports/reports.enum"

export const mockFleetOverviewReport: FleetOverviewReport = {
  reportInfo: {
    reportId: "RPT-FLEET-2025-10-001",
    reportType: "fleet_overview",
    generatedAt: "2025-10-30T09:00:00Z",
    period: {
      start: "2025-10-01T00:00:00Z",
      end: "2025-10-30T23:59:59Z",
    },
    totalVehicles: 64,
    companyId: "COMP-001",
    companyName: "BANF",
  },

  fleetSummary: {
    categories: [
      {
        category: VehicleType.EXCAVATOR,
        count: 15,
        active: 12,
        maintenance: 2,
        idle: 1,
        utilizationRate: 0.8,
      },
      {
        category: VehicleType.BULLDOZER,
        count: 8,
        active: 7,
        maintenance: 1,
        idle: 0,
        utilizationRate: 0.875,
      },
      {
        category: VehicleType.DUMP_TRUCK,
        count: 25,
        active: 22,
        maintenance: 2,
        idle: 1,
        utilizationRate: 0.88,
      },
      {
        category: VehicleType.WHEEL_LOADER,
        count: 10,
        active: 9,
        maintenance: 0,
        idle: 1,
        utilizationRate: 0.9,
      },
      {
        category: VehicleType.CRANE,
        count: 6,
        active: 5,
        maintenance: 1,
        idle: 0,
        utilizationRate: 0.833,
      },
    ],
    total: {
      count: 64,
      active: 55,
      maintenance: 6,
      idle: 3,
      utilizationRate: 0.859,
    },
  },

  keyPerformanceIndicators: [
    {
      name: "Average Fuel Efficiency",
      current: 18.5,
      target: 17.0,
      unit: "L/hr",
      status: "warning",
      trend: "declining",
    },
    {
      name: "Equipment Uptime",
      current: 85.9,
      target: 90.0,
      unit: "%",
      status: "warning",
      trend: "stable",
    },
    {
      name: "Avg Operating Hours/Day",
      current: 7.8,
      target: 8.0,
      unit: "hours",
      status: "warning",
      trend: "improving",
    },
    {
      name: "Tire Health Score",
      current: 82.0,
      target: 85.0,
      unit: "%",
      status: "warning",
      trend: "declining",
    },
    {
      name: "Maintenance On-Time",
      current: 91.0,
      target: 95.0,
      unit: "%",
      status: "warning",
      trend: "stable",
    },
  ],

  vehiclePerformance: [
    {
      vehicleId: "VH-1001",
      type: VehicleType.EXCAVATOR,
      model: "Komatsu PC200-11",
      operatingHours: 245,
      distance: 2205,
      fuelUsed: 4410,
      fuelEfficiency: 18.0,
      idleTime: 49,
      idlePercentage: 20.0,
      avgSpeed: 9.0,
      loadFactor: 0.75,
      performanceScore: 0.82,
      status: "good",
    },
    {
      vehicleId: "VH-1002",
      type: VehicleType.BULLDOZER,
      model: "Komatsu D65PX-18",
      operatingHours: 220,
      distance: 1760,
      fuelUsed: 4180,
      fuelEfficiency: 19.0,
      idleTime: 55,
      idlePercentage: 25.0,
      avgSpeed: 8.0,
      loadFactor: 0.8,
      performanceScore: 0.78,
      status: "good",
    },
    {
      vehicleId: "VH-1003",
      type: VehicleType.DUMP_TRUCK,
      model: "Hino Profia FR1EXEG",
      operatingHours: 280,
      distance: 3640,
      fuelUsed: 5040,
      fuelEfficiency: 18.0,
      idleTime: 42,
      idlePercentage: 15.0,
      avgSpeed: 13.0,
      loadFactor: 0.85,
      performanceScore: 0.88,
      status: "excellent",
    },
    {
      vehicleId: "VH-1004",
      type: VehicleType.WHEEL_LOADER,
      model: "Komatsu WA380-8",
      operatingHours: 260,
      distance: 2340,
      fuelUsed: 4420,
      fuelEfficiency: 17.0,
      idleTime: 52,
      idlePercentage: 20.0,
      avgSpeed: 9.0,
      loadFactor: 0.7,
      performanceScore: 0.8,
      status: "good",
    },
    {
      vehicleId: "VH-1005",
      type: VehicleType.CRANE,
      model: "Tadano GR-700N",
      operatingHours: 190,
      distance: 950,
      fuelUsed: 3420,
      fuelEfficiency: 18.0,
      idleTime: 57,
      idlePercentage: 30.0,
      avgSpeed: 5.0,
      loadFactor: 0.65,
      performanceScore: 0.72,
      status: "fair",
    },
  ],

  tireHealth: [
    {
      vehicleId: "VH-1001",
      tirePosition: TirePosition.FL,
      pressure: {
        current: 95,
        target: 100,
        unit: "psi",
      },
      temperature: 52,
      treadDepth: {
        current: 28,
        initial: 40,
        unit: "mm",
      },
      wearPercentage: 30,
      estimatedLifeRemaining: 4200,
      alertStatus: "ok",
      recommendation: "Normal operation",
    },
    {
      vehicleId: "VH-1001",
      tirePosition: TirePosition.FR,
      pressure: {
        current: 85,
        target: 100,
        unit: "psi",
      },
      temperature: 58,
      treadDepth: {
        current: 25,
        initial: 40,
        unit: "mm",
      },
      wearPercentage: 37.5,
      estimatedLifeRemaining: 3750,
      alertStatus: "warning",
      recommendation: "Check pressure - low by 15 psi",
    },
    {
      vehicleId: "VH-1001",
      tirePosition: TirePosition.RL,
      pressure: {
        current: 98,
        target: 100,
        unit: "psi",
      },
      temperature: 55,
      treadDepth: {
        current: 30,
        initial: 40,
        unit: "mm",
      },
      wearPercentage: 25,
      estimatedLifeRemaining: 4500,
      alertStatus: "ok",
      recommendation: "Normal operation",
    },
    {
      vehicleId: "VH-1001",
      tirePosition: TirePosition.RR,
      pressure: {
        current: 102,
        target: 100,
        unit: "psi",
      },
      temperature: 54,
      treadDepth: {
        current: 29,
        initial: 40,
        unit: "mm",
      },
      wearPercentage: 27.5,
      estimatedLifeRemaining: 4350,
      alertStatus: "ok",
      recommendation: "Normal operation",
    },
  ],

  tripAnalysis: [
    {
      tripId: "TR-2001",
      vehicleId: "VH-1001",
      vehicleType: VehicleType.EXCAVATOR,
      startTime: "2025-10-30T06:00:00Z",
      endTime: "2025-10-30T14:00:00Z",
      duration: 8.0,
      distance: 72,
      avgSpeed: 9.0,
      fuelUsed: 144,
      fuelEfficiency: 0.5,
      idleTimePercentage: 18.5,
      status: "completed",
    },
    {
      tripId: "TR-2002",
      vehicleId: "VH-1002",
      vehicleType: VehicleType.BULLDOZER,
      startTime: "2025-10-30T07:00:00Z",
      endTime: "2025-10-30T15:30:00Z",
      duration: 8.5,
      distance: 68,
      avgSpeed: 8.0,
      fuelUsed: 161.5,
      fuelEfficiency: 0.42,
      idleTimePercentage: 22.0,
      status: "completed",
    },
    {
      tripId: "TR-2003",
      vehicleId: "VH-1003",
      vehicleType: VehicleType.DUMP_TRUCK,
      startTime: "2025-10-30T05:30:00Z",
      endTime: "2025-10-30T16:00:00Z",
      duration: 10.5,
      distance: 168,
      avgSpeed: 16.0,
      fuelUsed: 189,
      fuelEfficiency: 0.89,
      idleTimePercentage: 12.0,
      status: "completed",
    },
  ],

  maintenanceSchedule: [
    {
      vehicleId: "VH-1001",
      vehicleType: VehicleType.EXCAVATOR,
      lastService: "2025-09-15",
      nextServiceDue: "2025-11-15",
      daysUntilDue: 16,
      serviceType: "250hr Service",
      priority: AlertPriority.MEDIUM,
      estimatedHours: 4.0,
      estimatedCost: 850,
      status: "scheduled",
    },
    {
      vehicleId: "VH-1002",
      vehicleType: VehicleType.BULLDOZER,
      lastService: "2025-10-01",
      nextServiceDue: "2025-11-01",
      daysUntilDue: 2,
      serviceType: "Oil Change",
      priority: AlertPriority.HIGH,
      estimatedHours: 2.0,
      estimatedCost: 450,
      status: "scheduled",
    },
    {
      vehicleId: "VH-1003",
      vehicleType: VehicleType.DUMP_TRUCK,
      lastService: "2025-08-20",
      nextServiceDue: "2025-10-28",
      daysUntilDue: -2,
      serviceType: "500hr Service",
      priority: AlertPriority.HIGH,
      estimatedHours: 6.0,
      estimatedCost: 1450,
      status: "overdue",
    },
    {
      vehicleId: "VH-1004",
      vehicleType: VehicleType.WHEEL_LOADER,
      lastService: "2025-09-25",
      nextServiceDue: "2025-11-25",
      daysUntilDue: 26,
      serviceType: "Hydraulic Check",
      priority: AlertPriority.LOW,
      estimatedHours: 3.0,
      estimatedCost: 550,
      status: "scheduled",
    },
    {
      vehicleId: "VH-1005",
      vehicleType: VehicleType.CRANE,
      lastService: "2025-10-10",
      nextServiceDue: "2025-12-10",
      daysUntilDue: 41,
      serviceType: "Annual Inspection",
      priority: AlertPriority.LOW,
      estimatedHours: 8.0,
      estimatedCost: 2200,
      status: "scheduled",
    },
  ],

  companySummary: [
    {
      companyName: "BANF",
      companyType: "owner",
      totalVehicles: 5,
      activeVehicles: 4,
      totalOperatingHours: 10250,
      totalDistance: 102500,
      totalFuel: 184500,
      avgUtilization: 0.8,
      performanceScore: 0.85,
    },
    {
      companyName: "Tokyu Heavy Industries",
      companyType: "construction",
      totalVehicles: 8,
      activeVehicles: 7,
      totalOperatingHours: 16800,
      totalDistance: 151200,
      totalFuel: 302400,
      avgUtilization: 0.875,
      performanceScore: 0.88,
    },
    {
      companyName: "Kansai Logistics Solutions",
      companyType: "logistics",
      totalVehicles: 12,
      activeVehicles: 11,
      totalOperatingHours: 26400,
      totalDistance: 316800,
      totalFuel: 475200,
      avgUtilization: 0.917,
      performanceScore: 0.91,
    },
    {
      companyName: "Chubu Construction Machinery",
      companyType: "construction",
      totalVehicles: 15,
      activeVehicles: 13,
      totalOperatingHours: 31500,
      totalDistance: 283500,
      totalFuel: 567000,
      avgUtilization: 0.867,
      performanceScore: 0.83,
    },
    {
      companyName: "Kyushu Transport Systems",
      companyType: "transportation",
      totalVehicles: 10,
      activeVehicles: 9,
      totalOperatingHours: 22000,
      totalDistance: 264000,
      totalFuel: 396000,
      avgUtilization: 0.9,
      performanceScore: 0.87,
    },
    {
      companyName: "Hokkaido Heavy Equipment",
      companyType: "construction",
      totalVehicles: 6,
      activeVehicles: 5,
      totalOperatingHours: 12600,
      totalDistance: 113400,
      totalFuel: 226800,
      avgUtilization: 0.833,
      performanceScore: 0.82,
    },
  ],
}

